language: go

go:
  - 1.9.x

cache:
  directories:
    - vendor

before_install:
  - npm install -g ganache-cli
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/mattn/goveralls
  - go get github.com/golang/dep/cmd/dep
  - go get golang.org/x/lint/golint
  - go get github.com/haya14busa/goverage
  - dep ensure

script:
  - go vet ./...
  - golint -set_exit_status `go list ./... | grep -Ev "(stackint/asm|vendor)"`
  - goverage -v -coverprofile=coverprofile.out ./...

after_success:
  - sed -i '/rpc.pb.go/d' coverprofile.out
  - sed -i '/bindings/d' coverprofile.out
  - sed -i '/cmd/d' coverprofile.out
  - goveralls -coverprofile=coverprofile.out -service=travis-ci -repotoken $COVERALLS_TOKEN
