language: go

go:
  - 1.9.x

cache:
  directories:
    - vendor

before_install:
  - npm install -g ganache-cli
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/mattn/goveralls
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/golang/lint/golint
  - dep ensure

script:
  - go vet ./...
  - golint -set_exit_status `go list ./... | grep -Ev "(stackint/asm|vendor)"`
  - go run cmd/testnetwork/main.go -sleep 10 &
  - sleep 10
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out stackint
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out identity
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out shamir
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out order
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out compute
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out logger
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out contracts/connection
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out contracts/dnr
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out network/dht
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out network/rpc
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out network
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out dark
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out hyperdrive
  - ginkgo -v --trace --cover --coverprofile coverprofile.out dark-node
  
after_success:
  - gocovmerge stackint/coverprofile.out identity/coverprofile.out shamir/coverprofile.out order/coverprofile.out compute/coverprofile.out logger/coverprofile.out contracts/connection/coverprofile.out contracts/dnr/coverprofile.out network/dht/coverprofile.out network/rpc/coverprofile.out network/coverprofile.out dark/coverprofile.out hyperdrive/coverprofile.out dark-node/coverprofile.out > coverprofile.out
  - sed -i '/rpc.pb.go/d' coverprofile.out
  - set -i '/bindings/d' coverprofile.out
  - goveralls -coverprofile=coverprofile.out -service=travis-ci -repotoken $COVERALLS_TOKEN
