language: go

go:
  - 1.9.x

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/mattn/goveralls

script:
  - ginkgo -v --trace --race --cover --coverprofile sss.coverpofile
  - goveralls -coverprofile=sss.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN