language: go

go:
  - 1.9.x

cache:
  directories:
    - vendor
    - $GOPATH/pkg/dep

before_install:
  - npm install -g ganache-cli
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/mattn/goveralls
  - go get github.com/golang/dep/cmd/dep
  - go get golang.org/x/lint/golint
  - go get github.com/loongy/covermerge
  - dep ensure

script:
  # - go vet ./...
  # - golint -set_exit_status `go list ./... | grep -Ev "(stackint/asm|vendor)"`
  # - golint `go list ./... | grep -Ev "(stackint/asm|vendor)"`
  - ginkgo -v --cover --coverprofile coverprofile.out ./...
  - covermerge crypto/coverprofile.out darknode/coverprofile.out darkocean/coverprofile.out delta/coverprofile.out dispatch/coverprofile.out identity/coverprofile.out logger/coverprofile.out order/coverprofile.out orderbook/coverprofile.out relay/coverprofile.out grpc/coverprofile.out shamir/coverprofile.out smpc/coverprofile.out stackint/coverprofile.out > coverprofile.out
  - sed -i '/.pb.go/d' coverprofile.out
  - sed -i '/bindings/d' coverprofile.out
  - sed -i '/cmd/d' coverprofile.out

after_success:
  - goveralls -coverprofile=coverprofile.out -service=travis-ci -repotoken $COVERALLS_TOKEN
