[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.2"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/jbenet/go-base58"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/multiformats/go-multiaddr"

[[constraint]]
  branch = "master"
  name = "github.com/multiformats/go-multihash"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/republicprotocol/go-do"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.3.0"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.18.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.10.0"

[prune]
  go-tests = true
